n=input('Digite qualquer coisa: ')
print(type(n))
print('É númerico? ',n.isnumeric())
print('É decimal? ',n.isdecimal())
print('É alfabeto? ',n.isalpha())
print('É espaço? ',n.isspace())
print('É maiúsculo? ',n.isupper())
print('É minúsculo? ',n.islower())
print('É um titulo? ',n.istitle())